### ISSUE TITLE
Teşekkürler

### ISSUE THREAD

**Issue by VB10** [cem256/manga_clean_arch#3]
Cem yayındayız reponu gördüm ilk anda çok hoşuma gitti kodlara bakıyoruz ama şimdiden eline emeğine sağlık

**Comment by MehmetKaranlik** [comment]
Eline sağlık @cem256

**Comment by cem256** [comment]
Çok teşekkür ederim Veli hocam. Geri bildiriminiz benim için çok değerli. En kısa zamanda yayın tekrarını izleyip eksiklikleri tamamlayacağım
